// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh51Ao-TrBwNRLf9RXecmAqJHIiHmuiuw',
    appId: '1:97248628227:web:20dcc09a6abfffdc4b8836',
    messagingSenderId: '97248628227',
    projectId: 'plant-shop-91901',
    authDomain: 'plant-shop-91901.firebaseapp.com',
    storageBucket: 'plant-shop-91901.firebasestorage.app',
    measurementId: 'G-HE5HY221DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcstj_pwch27bBTYJT1b_CVUsmeoxa93g',
    appId: '1:97248628227:android:63977ba87c0f3e9b4b8836',
    messagingSenderId: '97248628227',
    projectId: 'plant-shop-91901',
    storageBucket: 'plant-shop-91901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvldZ7HAwmIsUnSEhwNvvb_DShDw2BWmc',
    appId: '1:97248628227:ios:4eb54883752c92774b8836',
    messagingSenderId: '97248628227',
    projectId: 'plant-shop-91901',
    storageBucket: 'plant-shop-91901.firebasestorage.app',
    androidClientId: '97248628227-a86sks60a5nc0ro69g991gncv2ijvrnf.apps.googleusercontent.com',
    iosClientId: '97248628227-6al7vfkd3ub42q4ak9v0ti2gebenl5tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantshopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvldZ7HAwmIsUnSEhwNvvb_DShDw2BWmc',
    appId: '1:97248628227:ios:4eb54883752c92774b8836',
    messagingSenderId: '97248628227',
    projectId: 'plant-shop-91901',
    storageBucket: 'plant-shop-91901.firebasestorage.app',
    androidClientId: '97248628227-a86sks60a5nc0ro69g991gncv2ijvrnf.apps.googleusercontent.com',
    iosClientId: '97248628227-6al7vfkd3ub42q4ak9v0ti2gebenl5tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantshopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh51Ao-TrBwNRLf9RXecmAqJHIiHmuiuw',
    appId: '1:97248628227:web:20dcc09a6abfffdc4b8836',
    messagingSenderId: '97248628227',
    projectId: 'plant-shop-91901',
    authDomain: 'plant-shop-91901.firebaseapp.com',
    storageBucket: 'plant-shop-91901.firebasestorage.app',
    measurementId: 'G-HE5HY221DQ',
  );

}